# These are supported funding model platforms
 
github: [tomek-i]
patreon: user?u=26884777
buy_me_a_coffee: tomeki # Replace with a single Buy Me a Coffee username
#custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
